version: "3.9"

services:

  perlite:
    build:
      context: ./perlite
    container_name: perlite
   
    environment:
      - NOTES_PATH=Znanje
      - HIDE_FOLDERS=docs,private,trash

    volumes:
      - /mnt/twofiddy/data/znanje/:/var/www/perlite/Znanje:ro
    networks:
        External:
            ipv4_address: 192.168.100.8

  web:
    build:
        context: ./web 
    container_name: web   
    ports:
      - 80:80
    volumes_from: 
      - perlite       
    depends_on:
      - perlite
    networks:
        External:
            ipv4_address: 192.168.100.7


  
networks:
  External:
    name: external_net
    external: true